version = 1

exclude_patterns = [
    "BenchmarkingPortal.Web/wwwroot/lib/**",
    "BenchmarkingPortal.Migrations.Base/**"
]

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]