version: '3'

services:
  master:
    build: 
      context: .
      dockerfile: main.Dockerfile
    ports:
        - "15140:15140"
    command: bash -c "while ! ssh -o StrictHostKeyChecking=no worker 'exit'; do sleep 1; done && java -jar vcloud.jar master 1>/dev/null 2>&1"

  client:
    build: 
      context: .
      dockerfile: main.Dockerfile
    links:
      - "master"
    command: bash -c "while ! (echo >/dev/tcp/master/15140) &>/dev/null; do sleep 1; echo "Retrying.."; done && (echo 'auth USER'; sleep 1; echo 'run trivial') | java -jar vcloud.jar client"

  worker:
    build: 
      context: .
      dockerfile: worker.Dockerfile
    expose:
      - "22"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
