version: '3.4'

services:
  benchmarkingportal.web:
    image: ${DOCKER_REGISTRY-}benchmarkingportalweb
    build:
      context: .
      dockerfile: BenchmarkingPortal.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings__PostgressConnString=host=stackupPostgres;Port=5432;Database=Stackup;User Id=BossDude;Password=?7o#&mT39KST6BM8;"
      - "Kestrel__Certificates__Default__Path=./BenchmarkingPortal.pfx"
      - ASPNETCORE_URLS=https://localhost;http://localhost
      - ASPNETCORE_HTTPS_PORT=8001
    ports:
    # Replace the values on the left by the values on your launchSettings.json
      - "8000:80"
      - "8001:443"
  stackupPostgres:
    image: postgres
    container_name: stackupPostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=BossDude
      - POSTGRES_PASSWORD=?7o#&mT39KST6BM8
      - POSTGRES_DB=stackup_postgress
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  stackup_postgres_data:
  pgadmin-data:  